on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
      - name: build_and_deploy
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          BUILD_DIR: "."
          OUT_DIR: "public"
          TARGET_REPOSITORY: $REPOSITORY
          # Or if publishing to the same repo, use the automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          set -o pipefail
          echo "Starting deploy..."
          git config --global url."https://".insteadOf git://
          git config --global url."$GITHUB_SERVER_URL/".insteadOf "git@${GITHUB_HOSTNAME}":
          remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@${GITHUB_HOSTNAME}/${TARGET_REPOSITORY}.git"
          remote_branch=$PAGES_BRANCH
          
          npm install
          npm run build
          move dist public
          
          git checkout gh-pages
          
          git init
          git config user.name "GitHub Actions"
          git config user.email "github-actions-bot@users.noreply.${GITHUB_HOSTNAME}"
          git add .

          git commit -m "deploy"
          git push --force "${remote_repo}" master:"${remote_branch}"
